[package]

name = "emailaddress"
version = "0.1.0"
authors = ["Paul Woolcock <paul@woolcock.us>"]
description = "Simple email address type and parser"
homepage = "https://github.com/pwoolcoc/emailaddress"
keywords = ["email"]
license = "MIT"
